name: KoreanWonders
favicon: null
layout_spectrum: 0.8131508
typography_spectrum: 0.3474054
title: Korean Wonders
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4382863
  lightness: 0.07957764
  saturation: 0.9211402
  rhythmicContrast: 0.4745913
purpose: []
